pactravel:
  outputs:
    dev:
      dbname: pactravel-dwh
      host: localhost
      pass: mypassword
      port: 5434
      schema: final
      threads: 1
      type: postgres
      user: postgres
  target: dev